# Generated by Django 4.2.1 on 2024-09-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demoapp', '0002_delete_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='charts/')),
            ],
        ),
    ]
