# Generated by Django 4.2.1 on 2024-09-24 04:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardchart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
