# Generated by Django 4.2.1 on 2024-10-20 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0006_dashboardchart_user_pdffile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdffile',
            name='user',
        ),
        migrations.DeleteModel(
            name='DashboardChart',
        ),
        migrations.DeleteModel(
            name='PDFFile',
        ),
    ]
